### ISSUE TITLE
Specifics of mouse down + movement

### ISSUE THREAD

**Issue by alexhutman** [mackalex/pi-control-frontend#10]
> On mobile and web, moving the mouse (or finger) within the mousepad view will emit the mouse movement commands. I think my question is "when" will mouse movement commands be sent to the backend? When I want to take the client mouse on the web app out of the mousepad, then mouse movements will be emitted all the way to the mouse exiting the mousepad (let's say I want to move my client mouse to the textbox).
> 
> Additionally, will the iOS or Android client mousepad emit the mouse move command only when I tap, hold, drag, and then emit when released? Just trying to understand the ideal UX for this.
> 
> Otherwise, ack.

We'll have to think about what will happen on the website version with a mouse and keyboard since the main goal is the mobile apps, in which case it shouldn't be a problem. On mobile, you should easily be able to stop dragging your finger in order to reach outside of the mousepad, although I'm not quite sure how the JS event listeners differ on mobile. I tried testing using the Expo app on Android but it just kept perpetually loading.

The ideal UX is certainly hard to conjure up. I personally think that for the intent of the scope of the issue this PR is meant to address, this is fine. The main goal was to essentially just construct and "emit" the command on mouse move as a small goal. I think we can probably open a new issue for this discussion. Thoughts?

_Originally posted by @alexhutman in https://github.com/mackalex/pi-control-frontend/issues/9#issuecomment-2283035465_

**Comment by alexhutman** [comment]
Seems like there's a different notion of [pointerdown](https://developer.mozilla.org/en-US/docs/Web/API/Element/pointerdown_event) (+ [quite a few more pointer* events](https://developer.mozilla.org/en-US/docs/Web/API/Element/pointerdown_event#see_also)) vs [mousedown](https://developer.mozilla.org/en-US/docs/Web/API/Element/mousedown_event) events. So I think we'll want to handle the former instead.

We can of course still consider what would happen with mouse events, but that would imply someone is just controlling PiControl with a literal (presumably keyboard and) mouse from another computer. Since that very premise is pretty out of scope of the goal of PiControl, we can probably save that for later on and focus on the `pointer*` events for now.

**Comment by mackalex** [comment]
> Seems like there's a different notion of [pointerdown](https://developer.mozilla.org/en-US/docs/Web/API/Element/pointerdown_event) (+ [quite a few more pointer* events](https://developer.mozilla.org/en-US/docs/Web/API/Element/pointerdown_event#see_also)) vs [mousedown](https://developer.mozilla.org/en-US/docs/Web/API/Element/mousedown_event) event. So I think we'll want to handle these instead.
> 
> We can of course still consider what would happen with mouse events, but that would imply someone is just controlling PiControl with a literal (presumably keyboard and) mouse from another computer. Since that very premise is pretty out of scope of the goal of PiControl, we can probably save that for later on and focus on the `pointer*` events for now.

To be clear, you are saying that the webapp running on PC with keyboard and mouse is out of scope, and the mobile app is the initial scope. Is that correct? Just clarifying so I know what to prioritize on my end.

**Comment by alexhutman** [comment]
>Additionally, will the iOS or Android client mousepad emit the mouse move command only when I tap, hold, drag, and then emit when released? Just trying to understand the ideal UX for this.

@mackalex I think we're going to want it to work similarly, but the amount of time between `tap -> hold -> drag -> release` is going to be an eternity with 0 events being emitted. We should probably do something like this:
1. Pointer down event occurs. (Somehow) Determine if it was a tap or hold.
2. If it was just a tap, click the mouse. Not sure how we'd differentiate between left and right click...
3. Otherwise, it was a hold, so we should start emitting relative mouse movement events until release.

That's what the most intuitive sense to me, but not sure how we'd handle click + drags with that setup. There has to be some notion of a long press vs. tap vs. drag. Surely..

**Comment by alexhutman** [comment]
> > Seems like there's a different notion of [pointerdown](https://developer.mozilla.org/en-US/docs/Web/API/Element/pointerdown_event) (+ [quite a few more pointer* events](https://developer.mozilla.org/en-US/docs/Web/API/Element/pointerdown_event#see_also)) vs [mousedown](https://developer.mozilla.org/en-US/docs/Web/API/Element/mousedown_event) event. So I think we'll want to handle these instead.
> > We can of course still consider what would happen with mouse events, but that would imply someone is just controlling PiControl with a literal (presumably keyboard and) mouse from another computer. Since that very premise is pretty out of scope of the goal of PiControl, we can probably save that for later on and focus on the `pointer*` events for now.
> 
> To be clear, you are saying that the webapp running on PC with keyboard and mouse is out of scope, and the mobile app is the initial scope. Is that correct? Just clarifying so I know what to prioritize on my end.

Yes. But to my understanding, it looks like the `pointer*` events encapsulate all of the input for mice, styli, and touches. From [pointerdown](https://developer.mozilla.org/en-US/docs/Web/API/Element/pointerdown_event) for example:
>The `pointerdown` event is fired when a pointer becomes active. For mouse, it is fired when the device transitions from no buttons pressed to at least one button pressed. For touch, it is fired when physical contact is made with the digitizer. For pen, it is fired when the stylus makes physical contact with the digitizer.

At first I was thinking we should spend our time handling touch events only, but I think I understand the Pointer API a little better now. Assuming we do things correctly, it should work out of the box for all types of input once we switch. We shouldn't have to differentiate and handle them differently from my understanding.
