### ISSUE TITLE
Get raw socket connection working

### ISSUE THREAD

**Issue by alexhutman** [mackalex/pi-control-frontend#2]
## Scope:
- Just need to connect to the Pi, nothing more
- Need to use raw sockets, [this Node library](https://www.npmjs.com/package/raw-socket) might be of use

**Comment by mackalex** [comment]
On dat 💯

**Comment by alexhutman** [comment]
Wait... does Node have direct support for raw socket access?

https://nodejs.org/api/net.html#netcreateconnectionport-host-connectlistener
https://stackoverflow.com/a/18664857/6708303

**Comment by alexhutman** [comment]
Completed in #13
