### ISSUE TITLE
Create functional Touchpad component for relative mouse movement

### ISSUE THREAD

**Issue by alexhutman** [mackalex/pi-control-frontend#3]
## Scope:
- **Does not** have to be wired up yet. I.e., this does not depend on #2 
- Get working touchpad component that emits (even perhaps via `console.log`) the correct commands based on the server API for the [protocol](https://github.com/alexhutman/PiControl/blob/982139d3dd9490b184227ba7c1c213dc4bc22b80/src/serialize/protocol.h) and [relative mouse movements](https://github.com/alexhutman/PiControl/blob/982139d3dd9490b184227ba7c1c213dc4bc22b80/src/serialize/mouse.h#L37-L43)

**Comment by mackalex** [comment]
`console.log`ing once... Perhaps?
