### ISSUE TITLE
 Create functional Textbox component

### ISSUE THREAD

**Issue by alexhutman** [mackalex/pi-control-frontend#4]
## Scope:
- **Does not** have to be wired up yet. I.e., this does not depend on #2 
- Get working textbox component that emits (even perhaps via `console.log`) the correct commands based on the server API for the [protocol](https://github.com/alexhutman/PiControl/blob/982139d3dd9490b184227ba7c1c213dc4bc22b80/src/serialize/protocol.h) and [text entry](https://github.com/alexhutman/PiControl/blob/982139d3dd9490b184227ba7c1c213dc4bc22b80/src/backend/picontrol_backend.c#L92)

**Comment by mackalex** [comment]
Will impl and unit test 😎

**Comment by alexhutman** [comment]
### Notes:
- Currently, we just send 1 char. So the byte array should look like `[0x03, 0x01, 0x48]` to send the char `H`
- We also don't differentiate `keyUp` vs `keyDown` yet since the backend is hardcoded to translate `char -> keyPress`.
